language: c++
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
before_script:
  - git clone https://github.com/ICStoolbox/Commons.git
  - mkdir Commons/build
  - cd Commons/build
  - cmake ..
  - make 
  - make install
  - cd -
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make install
  - cd -
  - cd demos/2d
  - advection test.mesh -dt 0.001 -s test.sol -c test.chi.sol -o test.chi.sol
notifications:
  email: false
